In [21]:
import numpy as np
import optuna as opt
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

from students.kuzneczov.lesson3 import Exercise as ex

In [22]:
X, y = load_digits(return_X_y=True)

In [23]:
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

X_train, X_val, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size=0.25, random_state=42, stratify=y_train_val
)

In [33]:
def train(trial):
    hiddenLayerSize = trial.suggest_int("hidden layer", 1, 200)
    model = ex.create_model(
    ex.create_linear_layer(64, hiddenLayerSize),
    ex.create_sigmoid_layer(),
    ex.create_linear_layer(hiddenLayerSize, 10),
    ex.create_logsoftmax_layer(),
    )
    loss = ex.create_nll_loss()

    lr = trial.suggest_float("learning rate", 1e-5, 1e-1)
    batch_size = trial.suggest_int("batch size", 1, 100)

    ex.train_model(model, loss, X_train, y_train, lr, 10, batch_size)

    return (np.argmax(model.forward(X_val), axis=1) == y_val).mean()

study = opt.create_study(direction="maximize")
study.optimize(train, n_trials=100)

study.best_value, study.best_params

[I 2026-04-07 05:01:04,963] A new study created in memory with name: no-name-0275c3f3-09ce-4407-8f2d-c9e3adefa7cc
[I 2026-04-07 05:01:05,123] Trial 0 finished with value: 0.9444444444444444 and parameters: {'hidden layer': 169, 'learning rate': 0.032219250931557905, 'batch size': 27}. Best is trial 0 with value: 0.9444444444444444.
[I 2026-04-07 05:01:05,561] Trial 1 finished with value: 0.9722222222222222 and parameters: {'hidden layer': 62, 'learning rate': 0.07633861223048849, 'batch size': 3}. Best is trial 1 with value: 0.9722222222222222.
[I 2026-04-07 05:01:05,655] Trial 2 finished with value: 0.9194444444444444 and parameters: {'hidden layer': 102, 'learning rate': 0.014193888966784142, 'batch size': 32}. Best is trial 1 with value: 0.9722222222222222.
[I 2026-04-07 05:01:05,755] Trial 3 finished with value: 0.9555555555555556 and parameters: {'hidden layer': 123, 'learning rate': 0.08406475348413418, 'batch size': 43}. Best is trial 1 with value: 0.9722222222222222.
[I 2026-04

(0.9833333333333333,
 {'hidden layer': 132, 'learning rate': 0.08257256309324258, 'batch size': 7})

In [ ]:
y_test

array([5, 2, 8, 1, 7, 2, 6, 2, 6, 5, 0, 5, 9, 3, 4, 4, 2, 4, 9, 9, 6, 3,
       8, 1, 2, 5, 6, 0, 3, 4, 6, 7, 2, 6, 6, 6, 6, 5, 0, 9, 1, 7, 9, 6,
       5, 7, 5, 2, 7, 5, 0, 8, 5, 5, 3, 2, 4, 0, 0, 2, 7, 5, 6, 1, 3, 7,
       6, 5, 7, 0, 9, 0, 3, 8, 2, 5, 8, 2, 3, 5, 9, 3, 2, 7, 9, 6, 8, 1,
       0, 1, 2, 9, 4, 9, 1, 2, 7, 8, 4, 2, 6, 9, 3, 7, 3, 9, 6, 1, 1, 0,
       9, 2, 1, 6, 3, 4, 8, 7, 1, 0, 0, 4, 6, 5, 8, 2, 8, 8, 3, 0, 0, 8,
       6, 4, 3, 9, 3, 3, 3, 3, 0, 7, 0, 0, 1, 9, 5, 8, 1, 5, 0, 6, 6, 6,
       6, 1, 7, 7, 6, 7, 7, 8, 7, 3, 6, 5, 9, 0, 3, 8, 0, 9, 8, 1, 9, 5,
       9, 5, 8, 9, 9, 7, 9, 1, 9, 5, 4, 7, 3, 0, 4, 9, 7, 7, 5, 6, 5, 8,
       3, 4, 5, 4, 9, 2, 5, 5, 2, 1, 3, 8, 8, 9, 3, 6, 1, 0, 1, 4, 0, 5,
       5, 6, 6, 7, 4, 3, 8, 4, 1, 0, 7, 9, 2, 8, 4, 8, 4, 2, 4, 0, 0, 0,
       2, 6, 7, 0, 4, 5, 2, 2, 9, 0, 4, 6, 8, 2, 3, 9, 2, 3, 0, 6, 8, 7,
       1, 4, 4, 1, 1, 6, 3, 8, 1, 2, 5, 7, 8, 3, 2, 0, 3, 4, 1, 9, 9, 9,
       6, 3, 7, 1, 6, 9, 4, 7, 1, 8, 1, 3, 0, 5, 3,

In [26]:
modelrelu1 = ex.create_model(
    ex.create_linear_layer(64, 91),
    ex.create_relu_layer(),
    ex.create_linear_layer(91, 10),
    ex.create_logsoftmax_layer(),
)
loss = ex.create_nll_loss()
ex.train_model(modelrelu1, loss, X_train, y_train, 0.003996641319372173, 10, 1)

In [27]:
log_probs = modelrelu1.forward(X_test)
yres = np.argmax(log_probs, axis=1)
yres

array([5, 2, 8, 1, 7, 2, 6, 2, 6, 5, 0, 5, 9, 3, 4, 4, 2, 4, 9, 9, 6, 3,
       8, 1, 2, 5, 6, 0, 3, 4, 6, 7, 2, 6, 6, 6, 8, 5, 0, 9, 1, 7, 9, 6,
       5, 7, 5, 2, 7, 5, 0, 1, 5, 5, 3, 2, 4, 0, 0, 2, 7, 5, 6, 1, 3, 7,
       6, 5, 7, 0, 9, 0, 3, 8, 2, 5, 8, 2, 3, 5, 9, 3, 2, 7, 9, 6, 8, 1,
       0, 8, 2, 9, 4, 9, 1, 2, 7, 8, 4, 2, 6, 9, 3, 7, 3, 9, 6, 1, 1, 0,
       9, 2, 1, 6, 3, 4, 8, 7, 1, 0, 0, 4, 6, 5, 8, 2, 8, 1, 3, 0, 0, 8,
       6, 4, 3, 9, 3, 3, 3, 3, 0, 7, 0, 0, 1, 9, 5, 8, 1, 5, 0, 6, 6, 6,
       6, 1, 7, 7, 6, 7, 7, 8, 7, 3, 6, 5, 9, 0, 3, 8, 0, 9, 8, 1, 9, 5,
       9, 5, 8, 9, 9, 7, 9, 1, 9, 5, 4, 7, 3, 0, 4, 9, 7, 7, 5, 6, 5, 8,
       3, 4, 5, 4, 9, 2, 5, 5, 2, 1, 3, 8, 8, 9, 3, 6, 1, 0, 1, 4, 0, 5,
       5, 6, 6, 7, 4, 3, 8, 4, 8, 0, 7, 9, 2, 1, 4, 8, 4, 2, 4, 0, 0, 0,
       2, 6, 7, 0, 4, 5, 2, 2, 9, 0, 4, 6, 8, 2, 3, 9, 2, 3, 0, 6, 8, 7,
       1, 4, 4, 1, 1, 6, 3, 8, 1, 2, 5, 7, 8, 3, 2, 0, 3, 4, 1, 9, 9, 9,
       6, 3, 7, 1, 6, 9, 4, 7, 1, 8, 1, 3, 0, 5, 3,

In [28]:
metric = np.mean(yres == y_test)
metric

np.float64(0.9805555555555555)

In [41]:
modelrelu2 = ex.create_model(
    ex.create_linear_layer(64, 186),
    ex.create_relu_layer(),
    ex.create_linear_layer(186, 186),
    ex.create_relu_layer(),
    ex.create_linear_layer(186, 10),
    ex.create_logsoftmax_layer(),
)
ex.train_model(modelrelu2, loss, X_train, y_train, 0.05163154755074992, 10, 15)

In [42]:
log_probs = modelrelu2.forward(X_test)
yres = np.argmax(log_probs, axis=1)
yres

array([5, 2, 8, 1, 7, 2, 6, 2, 6, 5, 0, 5, 9, 3, 4, 4, 2, 4, 4, 9, 6, 3,
       8, 1, 2, 5, 6, 0, 3, 4, 6, 7, 2, 6, 6, 6, 8, 5, 0, 9, 1, 7, 9, 6,
       5, 7, 5, 2, 7, 5, 0, 1, 5, 5, 3, 2, 4, 0, 0, 2, 7, 5, 6, 1, 3, 7,
       6, 5, 7, 0, 9, 0, 3, 8, 2, 5, 8, 2, 3, 5, 4, 3, 2, 7, 9, 6, 8, 1,
       0, 1, 2, 9, 4, 9, 1, 2, 7, 8, 4, 2, 6, 9, 3, 7, 3, 9, 6, 1, 1, 0,
       9, 2, 1, 6, 3, 4, 8, 7, 1, 0, 0, 4, 6, 5, 8, 2, 8, 1, 3, 0, 0, 8,
       6, 4, 3, 9, 3, 3, 3, 3, 4, 7, 0, 0, 1, 9, 5, 8, 1, 5, 0, 6, 6, 6,
       6, 1, 7, 7, 6, 7, 7, 8, 7, 3, 6, 5, 9, 0, 3, 8, 0, 9, 8, 1, 9, 5,
       9, 5, 8, 9, 9, 7, 9, 1, 9, 5, 4, 7, 3, 0, 4, 9, 7, 7, 5, 6, 5, 8,
       3, 4, 5, 4, 9, 2, 5, 5, 2, 1, 3, 8, 8, 9, 3, 6, 1, 0, 1, 4, 0, 5,
       5, 6, 6, 7, 4, 3, 8, 4, 8, 0, 7, 9, 2, 8, 4, 8, 4, 2, 4, 0, 0, 0,
       2, 6, 7, 0, 4, 5, 2, 2, 9, 0, 4, 6, 8, 2, 3, 9, 2, 3, 0, 6, 8, 7,
       1, 4, 4, 1, 1, 6, 3, 8, 1, 2, 5, 7, 8, 3, 2, 0, 3, 4, 1, 9, 9, 9,
       6, 3, 7, 1, 6, 9, 4, 7, 1, 8, 1, 3, 0, 5, 3,

In [43]:
metric = np.mean(yres == y_test)
metric

np.float64(0.9805555555555555)

In [44]:
modelsigmoid1 = ex.create_model(
    ex.create_linear_layer(64, 132),
    ex.create_sigmoid_layer(),
    ex.create_linear_layer(132, 10),
    ex.create_logsoftmax_layer(),
)
ex.train_model(modelsigmoid1, loss, X_train, y_train, 0.08257256309324258, 10, 7)

In [45]:
log_probs = modelsigmoid1.forward(X_test)
yres = np.argmax(log_probs, axis=1)
yres

array([5, 2, 8, 8, 7, 2, 6, 2, 6, 5, 0, 5, 9, 3, 4, 4, 2, 4, 4, 9, 6, 3,
       8, 1, 2, 5, 6, 0, 3, 4, 6, 7, 2, 6, 6, 6, 8, 5, 0, 9, 1, 7, 9, 6,
       5, 7, 5, 2, 7, 5, 0, 1, 5, 5, 3, 2, 4, 0, 0, 2, 7, 5, 6, 1, 3, 7,
       6, 5, 7, 0, 9, 0, 3, 8, 2, 5, 8, 2, 3, 5, 9, 3, 2, 7, 9, 6, 8, 1,
       0, 8, 2, 9, 4, 9, 1, 2, 7, 8, 4, 2, 6, 9, 3, 7, 3, 9, 6, 1, 1, 0,
       9, 2, 1, 6, 3, 4, 8, 7, 1, 0, 0, 4, 6, 5, 8, 2, 8, 1, 3, 0, 0, 8,
       6, 4, 3, 9, 3, 3, 3, 3, 4, 7, 0, 0, 1, 9, 5, 8, 1, 5, 0, 6, 6, 6,
       6, 1, 4, 7, 6, 7, 7, 8, 7, 3, 6, 5, 9, 0, 3, 8, 0, 9, 8, 1, 9, 5,
       9, 5, 8, 9, 9, 7, 9, 1, 9, 5, 4, 7, 3, 0, 4, 9, 7, 7, 5, 6, 5, 8,
       3, 4, 5, 4, 9, 2, 5, 5, 2, 1, 3, 8, 8, 9, 3, 6, 1, 0, 1, 4, 0, 5,
       5, 6, 6, 7, 4, 3, 8, 4, 8, 0, 7, 9, 2, 8, 4, 8, 4, 2, 4, 0, 0, 0,
       2, 6, 7, 0, 4, 5, 2, 2, 9, 0, 4, 6, 8, 2, 3, 9, 2, 3, 0, 6, 8, 7,
       1, 4, 4, 1, 1, 6, 3, 8, 1, 2, 5, 7, 8, 3, 2, 0, 3, 4, 1, 9, 9, 9,
       6, 3, 7, 1, 6, 9, 4, 7, 1, 8, 1, 3, 0, 5, 3,

In [ ]:
metric = np.mean(yres == y_test)
metric

np.float64(0.9722222222222222)